services:
  - type: web
    name: n8n
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: N8N_PORT
        value: 10000
      - key: N8N_HOST
        value: 0.0.0.0